{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "carpool.mysql.fullname" . }}
  labels:
    {{- include "carpool.mysql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "carpool.mysql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "carpool.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "carpool.mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ include "carpool.mysql.fullname" . }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "carpool.mysql.fullname" . }}
{{- end }}
